# Generated by Django 5.2.11 on 2026-03-02 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("resume_content", models.TextField(blank=True, null=True)),
                ("self_description", models.TextField(blank=True, null=True)),
                ("match_score", models.IntegerField(default=0)),
                ("technical_questions", models.JSONField(default=list)),
                ("behavioral_questions", models.JSONField(default=list)),
                ("skill_gaps", models.JSONField(default=list)),
                ("preparation_plan", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
