# Generated by Django 5.2.11 on 2026-03-02 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewreport",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MockInterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_sessions",
                        to="core.interviewreport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                ("question_index", models.IntegerField(default=0)),
                ("user_answer", models.TextField()),
                ("ai_score", models.FloatField(blank=True, null=True)),
                ("ai_feedback", models.TextField(blank=True)),
                ("ai_strengths", models.JSONField(default=list)),
                ("ai_improvements", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.mockinterviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["question_index"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_role", models.CharField(blank=True, max_length=255)),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0-1", "Fresher (0-1 years)"),
                            ("1-3", "Junior (1-3 years)"),
                            ("3-5", "Mid-level (3-5 years)"),
                            ("5-10", "Senior (5-10 years)"),
                            ("10+", "Expert (10+ years)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=255)),
                (
                    "target_companies",
                    models.CharField(
                        blank=True, help_text="Comma-separated", max_length=500
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True, help_text="Comma-separated", max_length=1000
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
