# Generated by Django 5.2.9 on 2026-03-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_interviewreport_notes_mockinterviewsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewreport",
            name="target_company",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
