# Generated by Django 5.2.11 on 2026-03-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_interviewreport_target_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full-time"),
                    ("part-time", "Part-time"),
                    ("contract", "Contract"),
                ],
                default="full-time",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_joining",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(default="English", max_length=100),
        ),
    ]
