# Generated by Django 5.2.9 on 2026-03-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofile_city_userprofile_employment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewreport",
            name="coding_questions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("technical", "Technical"),
                    ("behavioral", "Behavioral"),
                    ("coding", "Coding"),
                ],
                default="technical",
                max_length=20,
            ),
        ),
    ]
