# Generated by Django 5.2.9 on 2026-03-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_interviewreport_coding_questions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="resume_file",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resume_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
