# Generated by Django 5.2.11 on 2026-03-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userprofile_resume_file_userprofile_resume_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewreport",
            name="ats_matching_keywords",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="interviewreport",
            name="ats_missing_keywords",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="interviewreport",
            name="ats_score",
            field=models.IntegerField(default=0),
        ),
    ]
