# Generated by Django 5.2.9 on 2026-03-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_interviewreport_ats_matching_keywords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="career_roadmap",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
