# Generated by Django 5.2.11 on 2026-03-09 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_userprofile_career_roadmap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeReviewAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="The feature context for the PR"),
                ),
                ("original_code", models.TextField(help_text="The starting code")),
                (
                    "buggy_code",
                    models.TextField(help_text="The code with inserted bugs"),
                ),
                (
                    "user_comments",
                    models.JSONField(
                        default=list,
                        help_text="List of line-specific comments made by the user",
                    ),
                ),
                ("ai_score", models.FloatField(blank=True, null=True)),
                (
                    "ai_feedback",
                    models.JSONField(
                        default=dict, help_text="Evaluation of caught vs missed bugs"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_review_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="STARSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "chat_history",
                    models.JSONField(
                        default=list,
                        help_text="Complete transcript of the conversation",
                    ),
                ),
                ("ai_score", models.FloatField(blank=True, null=True)),
                (
                    "ai_feedback",
                    models.JSONField(
                        default=dict,
                        help_text="Final analysis breaking down S-T-A-R components",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="star_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemDesignAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The system design problem given to the user"
                    ),
                ),
                (
                    "canvas_image",
                    models.TextField(
                        help_text="Base64 encoded image of the user's drawing"
                    ),
                ),
                ("ai_score", models.FloatField(blank=True, null=True)),
                (
                    "ai_feedback",
                    models.JSONField(
                        default=dict, help_text="Structured feedback on architecture"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_design_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
