# Generated by Django 5.2.9 on 2026-03-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_codereviewattempt_starsession_systemdesignattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemdesignattempt",
            name="user",
        ),
        migrations.DeleteModel(
            name="CodeReviewAttempt",
        ),
        migrations.DeleteModel(
            name="SystemDesignAttempt",
        ),
    ]
